version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
       - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2691
      - POSTGRES_DB=postgres
    networks:
      - innernetwork

  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      networks:
        - innernetwork

  jrka:
    build: ../../Downloads
    networks:
      - innernetwork


networks:
  innernetwork:
    driver: overlay
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - subnet: 192.168.10.0/24
    internal: true
    external: true